### ISSUE TITLE
Implement Ansible Collection structure for modules

### ISSUE THREAD

**Issue by titom73** [Hugh-Adams/Beta_CVP_Ansible_Modules#11]
As Ansible is moving to a new method to package and deliver 3rd part content, repository should start to adopt new collections structure as described on [their website](https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html)

```
collection/
├── docs/
├── galaxy.yml
├── plugins/
│   ├── modules/
│   │   └── module1.py
│   ├── inventory/
│   └── .../
├── README.md
├── roles/
│   ├── role1/
│   ├── role2/
│   └── .../
├── playbooks/
│   ├── files/
│   ├── vars/
│   ├── templates/
│   └── tasks/
└── tests/
```
__Resources:__
- [Creating a collection](https://galaxy.ansible.com/docs/contributing/creating_collections.html)
- [Collection Example](https://github.com/ansible-network/ansible_collections.arista.eos) for core EOS module
- [How to create collection structure](https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html#creating-collections)

First iteration will only provide module packaging and example playbooks. Additional roles and playbook for specific use cases might come in a second iteration.

> As it is in development, everything could change and this issue should be developed using `ansible@devel` branch to get all fixes.

To build package:

```shell
$ cd arista/cvp/
$ ansible-galaxy collection build --force
$ ansible-galaxy collection install *.tar.gz -p collections/ansible_collections/
```

Complete [example](https://gist.github.com/titom73/d450d32f6f5d85ae8fc25bd255b4be15) ci file

**Comment by titom73** [comment]
Development is going to take place in this branch: [issue-11-collection-packaging @ titom73/CVP_Ansible_Modules](https://github.com/titom73/CVP_Ansible_Modules/tree/issue-11-collection-packaging)

**Comment by titom73** [comment]
With this approach, when using `cv_configlet` with template, ansible raise error:

```shell
raise TemplateNotFoußnd(template)\njinja2.exceptions.TemplateNotFound: 
configlet.template.j2\n", "module_stdout": "", 
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Check [CI pipeline](https://gitlab.com/arista-projects/CVP_Ansible_Modules/-/jobs/279003513) for more outputs

**Comment by Hugh-Adams** [comment]
This work was completed in the official Arista Repo
